### PR TITLE
fix: updates deprecated ngOutletContext directive

### LINKED ISSUE #117: Error with ionic 3.9 and Angular 5: Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template'
Hi,

I try to use this library with ionic 3.9.2 and Angular 5, but it doesnt work.

The error message say:

```
Error: Template parse errors:
Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template'.
```
I check Angular API documentation, and it seems `ngOutletContex` has been deprecated in Angular 5.

https://angular.io/api/common/NgTemplateOutlet

I assume it can be fixed by replacing `ngOutletContex` with `ngTemplateOutletContex`.

### PR DESCRIPTION
**Pull request by CoreyCole**
fixes #117

### CODE REVIEW

**Comment by kadoshms** [comment]
Thanks!

**Comment by mgoku** [comment]
Thanks

**Comment by CoreyCole** [comment]
@kadoshms are you working on a separate branch for angular 5 support?

**Comment by kadoshms** [comment]
@CoreyCole I created a new branch and merged your commits into it :)

**Comment by CoreyCole** [comment]
Awesome, I'll take a look and see what else might need to be updated.

**Comment by sofiane01234** [comment]
Hi, i have a big problem when trying to install autocomplete module in my ionic project using npm command. I couldn't get the latest version containing formcontrol even if I precise it using @latest mention. Also after installation using cli I had some warning indicated that some peer modules are unmeeted????? Can anyone help.me pleaaaaase

**Comment by kadoshms** [comment]
It is not yet published...:)

**Comment by raphael22** [comment]
+1

**Comment by raphael22** [comment]
up

**Pull request merged**
